### ISSUE TITLE
Race Reports

### ISSUE THREAD

**Issue by Penut** [PikaTimer/PikaTimer#22]
I seem to have issues getting race reports to generate, is it possible to get a bit better documentation on using the Joey as the start and finish line, for say a square course crit race? or a time trial?

**Comment by segfaultcoredump** [comment]
Are you trying to use the same box for both the start and finish? 

If so, your start and end times cannot overlap and you need to fill out the "Start" and "End"  fields with valid start and end times for that particular location. Otherwise you will have start times loaded into the finish location or visa versa and the system will get really confused.

**Comment by segfaultcoredump** [comment]
With no updates in six months, I'm going to close this question.
