### ISSUE TITLE
Custom awards not showing up in Overall CSV results

### ISSUE THREAD

**Issue by anca-racehub** [PikaTimer/PikaTimer#29]
Context:
I try to generate awards for Age group which are not the same for Female and Men.
For example in a race I need to generate awards for Female under 35 and Female over 35 also for Male 15-19 years, Male 20-29 and Male 30+

I tried to achieve this using custom awards. 
I checked "visible on overall" and activated grouping by a field named "Age group" which contains the age groups described earlier (not the standard field, but a custom one). I named the award Category.

The expected behavior was that in the CSV generared in the results page type Overall (CSV) to find a column called Category# and the ranking according to my custom age groups.

If there is another way to achieve this please let me know.

![screenshot_9](https://user-images.githubusercontent.com/10059493/51923688-2918e300-23f4-11e9-934e-578ca3c78eb5.png)

PS: Thank you for this great software product. I am also a race timer (beginner) and software developer with a lot of years experience (not Java) and I can help you with the development or testing if you need help.

**Comment by segfaultcoredump** [comment]
CSV reports do not currently permit the display of awards.  

For an award to be displayed on the overall report, two things must be true. The award needs to be "Visible on Overall" and the "Show Awards" option needs to be checked on the Overall report. 

Only three of the overall reports are currently capable of displaying awards. Text, Responsive HTML, and JSON. The reason is that with these reports, I can populate additional data fields for each result in a 0..N fashion. 

But as I think about it, for the CSV report I can add it in the next release. I can simply add three columns per award to the CSV report: Award Title, Category, and Place.  This should accomplish what you are looking for.

**Comment by segfaultcoredump** [comment]
Take a look at the 1.5.2 release at https://github.com/PikaTimer/pikatimer/releases/tag/v1.5.2 to see if it fixes the issue.

**Comment by anca-racehub** [comment]
Thanks for the fix. It works as expected
