### ISSUE TITLE
working with RFID antenna

### ISSUE THREAD

**Issue by Mouxtaros** [PikaTimer/pikatimer#45]
Can I connect to my PC my RFID antenna and work this one program?

**Comment by segfaultcoredump** [comment]
No.  There is no integration for arbitrary RFID Readers at this point beyond the ones made by RFID Timing. 

You would need to either write an app that takes the data stream from your RFID system and drops it into a file that PikaTimer can read, or you would need to write the module that communicates with the reader and offer it as a pull request. There is no way for me to do it since I don't have access to the hardware for development.
